Shorten install instructions
webdev03/freecat pull request #1
Opened 2021-11-20 22:51 UTC by Darth-Ness

Pip3 works on Linux as well. I have tested this, as I was able to install the package this way.

2021-11-20 23:07 UTC, webdev03 commented
I think you need to change it to Linux not Linix

2021-11-20 23:08 UTC, webdev03 requested changes
I think that's it

2021-11-20 23:08 UTC, webdev03 commented on browser.py
> +  print("On macOS or Linix run:")
Linux

2021-11-21 13:34 UTC, Darth-Ness commented
Your fork was merged with FreeCat. So It's to late now.

2021-11-21 13:34 UTC, closed without merging